// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"es": &dictionary{index: esIndex, data: esData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"An error occurred":       1,
	"Failed to get profile":   3,
	"Failed to list profiles": 4,
	"Invalid profile ID":      0,
	"Profile not found":       2,
}

var enIndex = []uint32{ // 6 elements
	0x00000000, 0x00000013, 0x00000025, 0x00000037,
	0x0000004d, 0x00000065,
} // Size: 48 bytes

const enData string = "" + // Size: 101 bytes
	"\x02Invalid profile ID\x02An error occurred\x02Profile not found\x02Fail" +
	"ed to get profile\x02Failed to list profiles"

var esIndex = []uint32{ // 6 elements
	0x00000000, 0x00000017, 0x0000002c, 0x00000041,
	0x00000059, 0x00000072,
} // Size: 48 bytes

const esData string = "" + // Size: 114 bytes
	"\x02ID de perfil inválido\x02Ha ocurrido un error\x02Perfil no encontrad" +
	"o\x02Error al obtener perfil\x02Error al listar perfiles"

	// Total table size 311 bytes (0KiB); checksum: 4778579D
