// Code generated by mockery v2.23.1. DO NOT EDIT.

package uow

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, fn
func (_m *MockUnitOfWork) Do(ctx context.Context, fn UnitOfWorkBlock) error {
	ret := _m.Called(ctx, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, UnitOfWorkBlock) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockUnitOfWork_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn UnitOfWorkBlock
func (_e *MockUnitOfWork_Expecter) Do(ctx interface{}, fn interface{}) *MockUnitOfWork_Do_Call {
	return &MockUnitOfWork_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockUnitOfWork_Do_Call) Run(run func(ctx context.Context, fn UnitOfWorkBlock)) *MockUnitOfWork_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(UnitOfWorkBlock))
	})
	return _c
}

func (_c *MockUnitOfWork_Do_Call) Return(_a0 error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Do_Call) RunAndReturn(run func(context.Context, UnitOfWorkBlock) error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields:
func (_m *MockUnitOfWork) Store() UnitOfWorkStore {
	ret := _m.Called()

	var r0 UnitOfWorkStore
	if rf, ok := ret.Get(0).(func() UnitOfWorkStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UnitOfWorkStore)
		}
	}

	return r0
}

// MockUnitOfWork_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockUnitOfWork_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Store() *MockUnitOfWork_Store_Call {
	return &MockUnitOfWork_Store_Call{Call: _e.mock.On("Store")}
}

func (_c *MockUnitOfWork_Store_Call) Run(run func()) *MockUnitOfWork_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Store_Call) Return(_a0 UnitOfWorkStore) *MockUnitOfWork_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Store_Call) RunAndReturn(run func() UnitOfWorkStore) *MockUnitOfWork_Store_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockUnitOfWork interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnitOfWork(t mockConstructorTestingTNewMockUnitOfWork) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
